TRAIN:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 8
  EVAL_PERIOD: 4
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  FINETUNE: True
  CHECKPOINT_FILE_PATH: /gpfs/u/home/DPLD/DPLDsmms/scratch/projects/TimeSformer/expts/MiniKinetics_TimeSformer_divST_8x32_224_pt/checkpoints/checkpoint_epoch_00030.pyth
DATA:
  PATH_TO_DATA_DIR: /gpfs/u/home/DPLD/DPLDsmms/scratch/projects/TimeSformer/data_files/diving48
  PATH_LABEL_SEPARATOR: ';'
  NUM_FRAMES: 8
  SAMPLING_RATE: 32
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
TIMESFORMER:
  ATTENTION_TYPE: 'divided_space_time'
SOLVER:
  BASE_LR: 0.005
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 13, 19]
  LRS: [1, 0.1, 0.01]
  MAX_EPOCH: 20
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  OPTIMIZING_METHOD: sgd
MODEL:
  MODEL_NAME: vit_base_patch16_224
  NUM_CLASSES: 48
  ARCH: vit
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
  PRETRAINED: true
  LIN_PROBE: true
TEST:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 8
  NUM_ENSEMBLE_VIEWS: 1
  NUM_SPATIAL_CROPS: 3
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 4
NUM_SHARDS: 2
RNG_SEED: 0
OUTPUT_DIR: .
